### ISSUE TITLE
Config file burnList not working

### ISSUE THREAD

**Issue by huihiuhuai** [kotmatross28729/ItemPhysic-Legacy-Unofficial#1]
Items still burn
![image](https://github.com/user-attachments/assets/694b7ffc-a21a-4275-8021-526153cc17db)

**Comment by kotmatross28729** [comment]
Strange, but I can't reproduce it.

Post your `itemphysic.cfg` file, I'll check it (and modlist)

**Comment by huihiuhuai** [comment]
> Strange, but I can't reproduce it.
> 
> Post your `itemphysic.cfg` file, I'll check it (and modlist)

only creative core and item physic

**Comment by kotmatross28729** [comment]
Then check the integrity of the config and try to recreate it (copy the current config to the desktop, delete it from the config folder, then insert the values ​​from your previous config in the new configuration file after restarting) 
also check the `B:invertBurnList` option, it should be set to `false`

**Comment by kotmatross28729** [comment]
Oh wait, do you mean mod items? then yes, for some reason they don't work. The comparison system itself looks very strange, I will rewrite it when I can

**Comment by huihiuhuai** [comment]
> Oh wait, do you mean mod items? then yes, for some reason they don't work. The comparison system itself looks very strange, I will rewrite it when I can

the vanilla items i added also dont work

**Comment by kotmatross28729** [comment]
yeah, the system definitely needs a rewrite

**Comment by kotmatross28729** [comment]
### **Phew, it wasn't as easy as I thought (I hate logic functions!) but I managed to do this (I guess)**

## So here are the changes:

* Rewritten the entire list system (burnList and floatList) from scratch
* Added OreDictionary support (you can add huge groups of items without adding each one separately)
* Added item metadata support (for greater accuracy)

## And now visually (examples of use):

1)
```java
S:floatList <
        minecraft:carpet:13
>
B:invertFloatList=false
```
**Means that the carpet from minecraft with metadata 13 will float to the surface:**

![2024-09-28_16 26 54](https://github.com/user-attachments/assets/9017c5cd-adb8-43bb-9334-3bc856ff4e95)

---

2)
```java
S:floatList <
        minecraft:carpet:13
>
B:invertFloatList=true
```

**Means that all items EXCEPT the carpet from minecraft with metadata 13 will float to the surface:**

![2024-09-28_16 29 49](https://github.com/user-attachments/assets/80e823c9-db64-4c03-8ab1-405952087986)

---

3)
```java
S:burnList <
        minecraft:blaze_rod
        minecraft:nether_wart
        etfuturum:ancient_debris
>
B:invertBurnList=false
```

**Means all items except these 3 specified ones will burn:**

![2024-09-28_16 28 20](https://github.com/user-attachments/assets/4681654b-7cb0-4d0e-8583-2fed75279c67)

### **Note that `minecraft:nether_wart` is not in the default burnList and `etfuturum:ancient_debris` is a mod item**

---

4)
```java
S:burnList <
        minecraft:blaze_rod
        minecraft:nether_wart
        etfuturum:ancient_debris
>
B:invertBurnList=true
```

means ONLY these 3 specified ones will burn:

![2024-09-28_16 29 40](https://github.com/user-attachments/assets/dfb8b4a8-9c93-41bd-bf45-78b8a4abcbbf)

---

5) 
```java
S:floatList <
        stairWood
>
```
means that all blocks with OreDictionary stairWood will float:

![2024-09-28_16 35 32](https://github.com/user-attachments/assets/0935a21b-4432-4500-8061-ca3ab4913f02)

### **Well, it's pretty clear here, but still: note that stone stairs sink, although they are stairs too, that's because they are not part of the OreDictionary stairWood**

**Comment by kotmatross28729** [comment]
Оh, and please write if this works for you (maybe I closed it too early)

**Comment by huihiuhuai** [comment]
testing rn

**Comment by huihiuhuai** [comment]
![image](https://github.com/user-attachments/assets/e0a672eb-4c95-4486-b17f-be43f08af11f)
![image](https://github.com/user-attachments/assets/5c61124b-bcf0-4e23-8a25-a9d287f5a51f)
seems like you forgot to update the default config

**Comment by kotmatross28729** [comment]
Oh, you mean ignoremeta for vanilla items? I think I will do this, but in the next update, I don’t see the point in making a separate update for the default configuration. I also planned to add a couple of things from other mods (etfuturum, thaumcraft, hbm's ntm and maybe something else), and at the same time make a couple of ongoing TODOs that HRudyPlayZ once planned (not all, but at least a despawn option I guess)

Oh, and “backport some functions to be able to choose stuff like if an item should be cactus-resistant from newer versions” - sounds very simple

**Comment by kotmatross28729** [comment]
1.2.0 is out, and while I haven't fixed anything from HRudyPlayZ's list (yet), there's still a lot of work done:

1) Fully formatted README, added documentation (be sure to check it out), current TODO, and plans for the future

2) Added default support for some vanilla items, as well as Thaumcraft and etfuturum (hbm's ntm support is planned soon)

3) Added a new parameter to the config for floatList, which allows you to specify in what fluids the item floats (default is water). Useful when you want, for example, an item to float in lava, but sink in water (more details on usage in the README documentation)
