### ISSUE TITLE
Suggestion: Hide the "Power:*" text while keeping the custom throw

### ISSUE THREAD

**Issue by huihiuhuai** [kotmatross28729/ItemPhysic-Legacy-Unofficial#3]
![image](https://github.com/user-attachments/assets/bee9bf2c-8c07-40e6-ba81-8241a6957c94)

**Comment by Omgise** [comment]
Good suggestion! I also think this text is quite obstructive :D

**Comment by kotmatross28729** [comment]
If I understand correctly, you are proposing to hide the "Power:*" text above the main HUD, while leaving the ability to throw items further?

While I don't think this should be the default (since you don't know how far you're going to throw it), I can make it as config option

**Comment by Omgise** [comment]
> If I understand correctly, you are proposing to hide the "Power:*" text above the main HUD, while leaving the ability to throw items further?

Or can you make the text on the HUD translatable through a lang file?

**Comment by kotmatross28729** [comment]
> Or can you make the text on the HUD translatable through a lang file?

Yeah, it's possible

**Comment by huihiuhuai** [comment]
i prefer to hide it

**Comment by kotmatross28729** [comment]
Added the ability to translate "Power" via a .lang file, as well as an option in the config to completely disable it:


https://github.com/user-attachments/assets/f74cf51c-e595-4c5b-8e59-017f35865e2c



P.S: it’s funny, but for about an hour I didn’t figure out why it didn’t see the value from the .lang file, and the problem turned out to be that itemphysic didn't exist as a mod 0_0. It implemented `cpw.mods.fml.common.DummyModContainer` rather than the standard `cpw.mods.fml.common.Mod`. Therefore, we can say that in 1.2.3 itemphysic is now officially a mod

**Comment by huihiuhuai** [comment]
thank you for the amazing job on this mod!
