### ISSUE TITLE
 The item that was thrown out looks a bit strange.

### ISSUE THREAD

**Issue by Omgise** [kotmatross28729/ItemPhysic-Legacy-Unofficial#5]
https://github.com/user-attachments/assets/b7af444c-9e4c-4115-ab7c-1589cfe2a077

https://github.com/user-attachments/assets/06c4dcb3-36d8-4e1b-aca7-fb5fceea8be1

**Comment by kotmatross28729** [comment]
Yes, it's a known issue. I'll try to fix it in the future.

By the way, a little clarification on this issue(s):

1) Items with a 3D model don't rotate - unfixable, due to the way TESR works in forge (Personally, maybe it's even for the best: imagine that you throw a huge 3D tileentity, and it uncontrollably rotates, blocking the entire field of view.)

2) The thing you see next to the model is the texture of the item. Usually you don't see it, because mods hide it when the item is in the world/inventory and replace it with a 3D model.

**Comment by kotmatross28729** [comment]
I guess we doin fixes now

https://github.com/user-attachments/assets/d59353fc-3cc4-4354-9f19-e9bcb086e7d3
