### ISSUE TITLE
When an item is carried away by ants in Mo' Creatures Legacy, the item spins uncontrollably on its body.

### ISSUE THREAD

**Issue by Omgise** [kotmatross28729/ItemPhysic-Legacy-Unofficial#6]
https://github.com/user-attachments/assets/7223ce82-5766-44cc-bcbe-b5a90ce29836

**Comment by kotmatross28729** [comment]
Thanks for the report. However this is unfixable until we switch to mixins

You see, any item that isn't on the ground will rotate, but here is the code from Mo' Creatures Legacy:
```java
    private void exchangeItem(EntityItem entityItem)
    {
        EntityItem cargo = new EntityItem(worldObj, posX, posY+0.2D, posZ, entityItem.getEntityItem());
        entityItem.setDead();
        if (MoCreatures.isServer()) worldObj.spawnEntityInWorld(cargo);
    }
```

From this code you can see that the ant spawns an item 0.2 above its position - therefore the item is considered not to be on the ground. And, it is impossible to fix this now, but, when we switch to mixins, it will be possible to make an Inject into this code, and mark that this item should not rotate (Like a blacklist with items, when checks come to understand whether the item should rotate (lies on ground) we will also check whether it is in this blacklist, and if so, cancel rotations)

So yes, it can be fixed, but a little later

**Comment by kotmatross28729** [comment]
I think Mo' Creatures ants are a little...um... weird...


https://github.com/user-attachments/assets/1fecac5a-5f75-41c2-b667-7ef176e8c2e7



(P.S: this happens even without ItemPhysic)

Legal™ dupe btw

**Comment by kotmatross28729** [comment]
https://github.com/user-attachments/assets/210d7852-7a93-43c0-a8f6-38899e44f231


https://github.com/user-attachments/assets/28667254-fc62-431a-b9ce-dad6e19204d7






So, this was even easier than I thought - we don't even have to use mixins for this. 
Oh, and this should fix the spinning issue in general, not just for Mo' Creatures/Thaumcraft, but for other mods that implement things like pedestals (chocolateQuest, YeGamolChattels, etc.). 

The fix itself is changing the check for whether item should spin. Before, it only checked its position on the ground (and as we know, on pedestals, the item is not considered to be on the ground). Now we also check if the item's Y position has changed since the previous tick, and if so, we consider it to be falling, so we apply rotation. And if not, we consider it to be on a pedestal (not on the ground, but hasn't moved in Y since the previous tick).

One more thing: I won't uploading 1.2.6 yet, because I want to fully complete the TODO. So here's the prerelease version, if you want to try it out:

[1.2.6-prerelease.zip](https://github.com/user-attachments/files/17244402/1.2.6-prerelease.zip)
